# Generated by Django 5.2.16 on 2026-07-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(max_length=32)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('module', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=512)),
                ('detail', models.TextField(blank=True)),
                ('http_method', models.CharField(blank=True, max_length=16)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_dashbo_created_f7f3e9_idx'), models.Index(fields=['actor_role', '-created_at'], name='core_dashbo_actor_r_422c39_idx')],
            },
        ),
    ]
