# Generated by Django 5.2.16 on 2026-07-25 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAcademicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('MID_EXAM', 'Mid Exam'), ('FINAL_EXAM', 'Final Exam')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(help_text='Ethiopian calendar year when this item was first added.', on_delete=django.db.models.deletion.PROTECT, related_name='grade_academic_items', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'grade_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GradeAcademicItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='academics/grade-items/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='academics.gradeacademicitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gradeacademicitem',
            index=models.Index(fields=['item_type', 'grade_level'], name='academics_g_item_ty_e4b1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeacademicitem',
            index=models.Index(fields=['academic_year'], name='academics_g_academi_d21e95_idx'),
        ),
    ]
