# Generated by Django 5.2.16 on 2026-07-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradeacademicitem_gradeacademicitemattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeacademicitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_academic_items', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='gradeacademicitem',
            index=models.Index(fields=['subject', 'item_type'], name='academics_g_subject_ef2af6_idx'),
        ),
    ]
