# Generated by Django 5.2.16 on 2026-07-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_timetable_section_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day_of_week', 'period_number', 'start_time']},
        ),
    ]
