# Generated by Django 5.2.16 on 2026-07-26 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeacademicitem',
            name='academic_year',
            field=models.ForeignKey(
                blank=True,
                help_text='Ethiopian calendar year when this item was first added (not used for materials).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='grade_academic_items',
                to='academics.academicyear',
            ),
        ),
        migrations.AlterField(
            model_name='gradeacademicitem',
            name='item_type',
            field=models.CharField(
                choices=[
                    ('ASSIGNMENT', 'Assignment'),
                    ('MID_EXAM', 'Mid Exam'),
                    ('FINAL_EXAM', 'Final Exam'),
                    ('MATERIAL', 'Material'),
                ],
                max_length=20,
            ),
        ),
    ]
