# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_gradeexamscheduleplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamscheduleplan',
            name='week_start_date',
            field=models.DateField(
                blank=True,
                help_text='Monday of the exam week (maps weekday rows to calendar dates).',
                null=True,
            ),
        ),
    ]
