# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_gradeexamscheduleplan_week_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamscheduleplan',
            name='scheduled_weekdays',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered weekday numbers (1=Mon … 7=Sun) shown on the schedule.',
            ),
        ),
    ]
