# Generated by Django 5.2.16 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_gradeexamscheduleplan_scheduled_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamscheduleentry',
            name='schedule_slot_index',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Index into the plan scheduled_weekdays list for this exam row.',
            ),
        ),
        migrations.AlterModelOptions(
            name='gradeexamscheduleentry',
            options={
                'ordering': ['grade_level', 'schedule_slot_index', 'exam_date', 'start_time'],
                'verbose_name': 'Grade exam schedule entry',
                'verbose_name_plural': 'Grade exam schedule entries',
            },
        ),
    ]
