# Generated by Django 5.2.16 on 2026-07-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
