# Generated by Django 5.2.16 on 2026-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentenrollmentsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgradereport',
            name='class_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgradereport',
            name='class_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
